double sin(double x);
double cos(double x);
double tan(double x);
double pow(double x, double w);
double ln(double x);
double arcsin(double x);
double arccos(double x);
double arctan(double x);
double fast_inv_sqrt(double x);
double factorial(double x);
void dtf(double decimal, int* numerator, int* denominator);
