import ctypes
import matplotlib.pyplot as plt
import numpy as np

lib=ctypes.CDLL('./differential2.so')  #loading the .so shared lib which was created from c code

lib.Xco.restype=ctypes.POINTER(ctypes.c_double) #Xco returns a pointer to an array
lib.Yco.restype=ctypes.POINTER(ctypes.c_double) #Yco returns a pointer to an array

#calling C functions to get x and y coordinates
result1=lib.Xco()
result2=lib.Yco()

x_coords=list([])
y_coords=list([])

#looping through points and store them in a list

for i in range(1000000):
    x_coords.append(result1[i])
    y_coords.append(result2[i])

#finding the points to plot the actual curve
y_ac=np.linspace(0,10.8,5000)
x_ac=2*((np.e)**(y_ac))-(1+(y_ac))
#plotting the points of the curve generated by c
plt.scatter(x_coords, y_coords, label="sim", s=40)
#plotting the points of actual curve
plt.plot(x_ac,y_ac,'.',color='red',label="theory")


plt.xlabel('X')
plt.ylabel('Y')
plt.grid(True)
plt.legend(loc='best')
plt.show()
